tests: add/improve mount shared-subtree tests
Signed-off-by: Karel Zak <kzak@redhat.com>

diff --git a/tests/ts/mount/shared-subtree b/tests/ts/mount/shared-subtree
--- a/tests/ts/mount/shared-subtree
+++ b/tests/ts/mount/shared-subtree
@@ -7,19 +7,6 @@ TS_DESC="shared-subtree"
 ts_init "$*"
 ts_skip_nonroot
 
-function get_attr() 
-{
-	# It's usually stupid idea to use 'grep | awk',
-	# but use paths in awk /regex/ is too tricky...
-	#
-	# TODO; improve libmount and findmnt to return the
-	#       shared-subtree flags
-	#
-	echo $(grep "$1" /proc/self/mountinfo | \
-		awk '{print $7}' | \
-		awk -F ':' '{ print $1 }')
-}
-
 [ -d $TS_MOUNTPOINT ] || mkdir -p $TS_MOUNTPOINT
 
 # bind
@@ -35,23 +22,59 @@ MOUNTPOINT="$TS_MOUNTPOINT"
 
 ts_init_subtest "make-shared"
 $TS_CMD_MOUNT --make-shared $MOUNTPOINT >> $TS_OUTPUT 2>&1
-echo  "$(get_attr $MOUNTPOINT)" >> $TS_OUTPUT
+$TS_CMD_FINDMNT -nr --target $MOUNTPOINT -o PROPAGATION >> $TS_OUTPUT
 ts_finalize_subtest
 
 ts_init_subtest "make-private"
 $TS_CMD_MOUNT --make-private $MOUNTPOINT >> $TS_OUTPUT 2>&1
-echo  "$(get_attr $MOUNTPOINT)" >> $TS_OUTPUT
+$TS_CMD_FINDMNT -nr --target $MOUNTPOINT -o PROPAGATION >> $TS_OUTPUT
 ts_finalize_subtest
+
 
 ts_init_subtest "make-unbindable"
 $TS_CMD_MOUNT --make-unbindable $MOUNTPOINT >> $TS_OUTPUT 2>&1
-echo  "$(get_attr $MOUNTPOINT)" >> $TS_OUTPUT
+$TS_CMD_FINDMNT -nr --target $MOUNTPOINT -o PROPAGATION >> $TS_OUTPUT
+ts_finalize_subtest
+
+# clean up
+$TS_CMD_UMOUNT $MOUNTPOINT
+
+
+ts_init_subtest "bind-shared"
+$TS_CMD_MOUNT --make-shared \
+	      --bind $MOUNTPOINT $MOUNTPOINT >> $TS_OUTPUT 2>&1
+$TS_CMD_FINDMNT -nr --target $MOUNTPOINT -o PROPAGATION >> $TS_OUTPUT
+$TS_CMD_UMOUNT $MOUNTPOINT
 ts_finalize_subtest
 
 
-# clean up
-$TS_CMD_UMOUNT $TS_MOUNTPOINT
-rmdir $TS_MOUNTPOINT
+#
+# block dev based mounts
+#
+DEVICE=$(ts_device_init)
+[ "$?" == 0 ] || ts_die "Cannot init device"
+
+mkfs.ext3 $DEVICE &> /dev/null || ts_die "Cannot make ext3 on $DEVICE" $DEVICE
+ts_device_has "TYPE" "ext3" $DEVICE || ts_die "Cannot find ext3 on $DEVICE" $DEVICE
+
+
+ts_init_subtest "mount-private"
+$TS_CMD_MOUNT --make-private --make-unbindable \
+	      $DEVICE $MOUNTPOINT >> $TS_OUTPUT 2>&1
+$TS_CMD_FINDMNT -nr --target $MOUNTPOINT -o PROPAGATION >> $TS_OUTPUT
+$TS_CMD_UMOUNT $MOUNTPOINT
+ts_finalize_subtest
+
+ts_init_subtest "mount-private-ro"
+$TS_CMD_MOUNT $DEVICE $MOUNTPOINT -o ro,private >> $TS_OUTPUT 2>&1
+$TS_CMD_FINDMNT -nr --target $MOUNTPOINT -o PROPAGATION >> $TS_OUTPUT
+$TS_CMD_FINDMNT -nr --target $MOUNTPOINT -o VFS-OPTIONS >> $TS_OUTPUT
+$TS_CMD_UMOUNT $MOUNTPOINT
+ts_finalize_subtest
+
+
+ts_device_deinit $DEVICE
+rmdir $MOUNTPOINT
 
 ts_log "Success"
 ts_finalize
