tools: improve in-repo check
Signed-off-by: Karel Zak <kzak@redhat.com>

diff --git a/tools/git-tp-sync b/tools/git-tp-sync
--- a/tools/git-tp-sync
+++ b/tools/git-tp-sync
@@ -52,11 +52,10 @@ while [[ $# -gt 0 ]]; do
 	esac
 done
 
-git rev-parse --is-inside-work-tree &> /dev/null
-if [ "$?" -ne 0 ]; then
-	echo "Must be called within a Git working tree."
+git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
+	echo "Error: Not inside a Git repository." >&2
 	exit 1
-fi
+}
 
 # default to all dirs defined by TP_PROJECTS
 if [ ${#DIRS[@]} -eq 0 ]; then
diff --git a/tools/git-version-bump b/tools/git-version-bump
--- a/tools/git-version-bump
+++ b/tools/git-version-bump
@@ -11,12 +11,10 @@ if [ -z "$VERSION" ]; then
 	exit 1
 fi
 
-git rev-parse --is-inside-work-tree &> /dev/null
-if [ "$?" -ne 0 ]; then
-	echo "Must be called within a Git working tree."
+git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
+	echo "Error: Not inside a Git repository." >&2
 	exit 1
-fi
-
+}
 
 function bump_news_version {
 	local version="$1"
